apiVersion: v1
kind: Pod
metadata:
  labels:
    role: wbe-frontend
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - containerPort: 80
          name: web
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nfs
  volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: nfs