apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: envoy-config
initializers:
  #这个名字必须至少包括两个"."
  - name: envoy.initializer.kubernetes.io
    rules:
      - apiGroups:
          # ""就是core API Group 的意思
          - ""
        apiVersion:
          - v1
        resources:
          - pods