apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: busybox
      command: ['sh','-c','echo Hello Kubernetes! && sleep 3600']
    - name: envoy
      image: lyft/envoy:845747b88f102c0fd262ab234308e9e22f693a1
      command: ["/usr/local/bin/envoy"]
      .**..**