apiVersion: v1
kind: Pod
metadata:
  name: with-toleration
spec:
  containers:
    - name: busybox
  tolerations:
    - key: node.kubernetes.io/unschedulable
      operator: Exists
      effect: NoSchedule